language: python
cache: pip
matrix:
  include:
    - python: 3.8
    - python: 3.7
    - python: 3.6
    - python: 3.5
install:
  - pip install tox coveralls
script:
  - tox
after_success:
  - coveralls