#:kivy 1.0

TabbedPanel:
    size_hint: 1.0, 1.0
    pos_hint: {'center_x': .5, 'center_y': .5}
    do_default_tab: False

    TabbedPanelItem:
        text: 'Config'
        Label:
            text: 'config'
    TabbedPanelItem:
        text: 'Sync'
        Label:
            text: 'sync'
    TabbedPanelItem:
        text: 'iTunes'
        Label:
            text: 'iTunes'
    TabbedPanelItem:
        text: 'Serato DJ Pro'
        Label:
            text: 'Serato DJ Pro'
